# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['url_browser_rule_advanced_pyqt.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'unittest',
        'pydoc',
        'doctest',
        'sqlite3',
        'tkinter',
        'turtle',
        'win32com',
        'pywin32',
        'numpy',
        'scipy',
        'matplotlib',
        'sympy',
        'pandas',
        'PIL',
        'PyQt5.QtSvg',
        'PyQt5.QtSql',
        'PyQt5.QtOpenGL',
        'PyQt5.QtPrintSupport',
        'PyQt5.QtMultimedia',
        'PyQt5.QtMultimediaWidgets',
        'PyQt5.QtWebEngine',
        'PyQt5.QtWebEngineCore',
        'PyQt5.QtWebEngineWidgets',
        'PyQt5.QtQml',
        'PyQt5.QtQuick',
        'PyQt5.QtQuickWidgets',
        'PyQt5.QtSensors',
        'PyQt5.QtSerialPort',
        'PyQt5.QtPositioning',
        'PyQt5.QtLocation',
        'PyQt5.QtNfc',
        'PyQt5.QtBluetooth',
        'PyQt5.QtHelp',
        'PyQt5.QtDesigner',
        'PyQt5.QtAxContainer',
    ],
    noarchive=False,
    optimize=2,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [('O', None, 'OPTION'), ('O', None, 'OPTION')],
    name='URLBrowserRule',
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['url.ico'],
)
